variable "public_key_comment" {
    default     = ""
    description = "An optional comment about the public key."
    type        = string
}

variable "pub_key_file" {
    default     = "public_key.pem"
    description = "The encoded public key that you want to add to CloudFront to use with features like field-level encryption."
    type        = string
}

variable "public_key_name" {
    default     = ""
    description = "The name for the public key. By default generated by Terraform."
    type        = string
}

variable "key_group_comment" {
    default     = ""
    description = "A comment to describe the key group."
    type        = string
}

variable "key_group_name" {
    default =   ""
    description = "A name to identify the key group."
    type        = string
}