name: Version Increment

on:
  workflow_dispatch
  # push:
  #   branches: [master]

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
        
      # - name: Get tags
      #   run: git fetch --tags origin
      
      - name: Get current version
        run: |
          echo "current_version=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      - name: Print current version
        run: |
          echo "${{ env.current_version }}"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: path
