name: Make docs

on:
  workflow_dispatch:

env:
  TFD_VERSION : "v0.16.0"
  OUTPUT_MODE : "inject"
  OUTPUT_FILE : "README.md"


jobs:
  directories:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }}
    steps:
      - uses: actions/checkout@v2
      - id: set-dirs
        run: echo "::set-output name=dir::$(ls -d */ | jq -R -s -c 'split("\n")[:-1]')"

  make_readme:
    runs-on: ubuntu-latest
    # continue-on-error: false
    needs: [directories]
    # strategy:
    #   matrix:
    #     dir: ${{fromJson(needs.directories.outputs.dir)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install terraform docs
        uses: ./.github/actions/install-terraform-docs
        with:
          tfd_version: ${{ env.TFD_VERSION }}
      
      - name: Make docs
        run: |
          for item in */ ; do
            /usr/local/terraform-docs markdown table --output-file ${{ env.OUTPUT_FILE }} --output-mode ${{ env.OUTPUT_MODE }} "$item"
          done

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Modified README.md"
          branch: ${{ github.ref }}
      

