name: CI

on:
  push:
    branches: [master]

jobs:
  directories:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }}
    steps:
      - uses: actions/checkout@v2
      - id: set-dirs
        run: echo "::set-output name=dir::$(ls -d */ | jq -R -s -c 'split("\n")[:-1]')"

  loop:
    runs-on: ubuntu-latest
    needs: [directories]
    strategy:
      matrix:
        dir: ${{fromJson(needs.directories.outputs.dir)}} 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installing tfswitch
        run: curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | sudo bash
        
      - name: Check ${{matrix.dir}}
        working-directory: ${{matrix.dir}}
        run: |
          ls -al
          tfswitch
          terraform init -backend=false
          terraform validate